import type { Metadata } from "next";
import { Inter_Tight, Montserrat } from "next/font/google";
import "./globals.css";

const Inter = Inter_Tight({
  variable: "--font-inter",
  subsets: ["latin"],
});

const Montserrats = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prompt Baazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Inter.variable} ${Montserrats.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
